slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: base_link
    map_frame: map
    use_odom: true
    base_frame: base_link
    publish_tf_map: true
    resolution: 0.05
    scan_topic: scan
    odom_topic: scan_odom 
    mode: mapping
    minimum_travel_distance: 0.05
