slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: base_link
    map_frame: map
    odom_frame: base_link
    use_odom: false
    base_frame: base_link
    publish_tf_map: true
    resolution: 0.05
    scan_topic: scan
    mode: mapping
    minimum_travel_distance: 0.05
