slam_toolbox:
  ros__parameters:
    use_sim_time: true 
    odom_frame: odom
    map_frame: map
    use_odom: true
    base_frame: base_link
    publish_tf_map: true
    resolution: 0.05
    scan_topic: scan
    odom_topic: odom_rf2o 
    mode: mapping
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.1
    map_update_interval: 5.0
    transform_publish_period: 0.02
